title: Monitoring the Power Platform
description: An examination and guidance into monitoring transaction, operational and high value workloads with the Power Platform by Ali Youssefi
theme: jekyll-theme-slate
